name: deshifarmer
description: A agro flutter based project
version: 3.2.1+30
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # animated_bottom_navigation_bar: ^1.2.0
  animations: ^2.0.7
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.1
  dotted_border: ^2.0.0+3
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_crashlytics: ^3.4.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.3
  flutter_image_stack: ^0.0.7
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.14.4
  # freezed: ^2.4.5
  geolocator: ^10.0.0
  google_fonts: ^6.0.0
  http: ^1.1.0
  image_picker: ^1.0.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  lottie: ^2.6.0
  mime: ^1.0.4
  multi_dropdown: ^2.0.1
  path_provider: ^2.0.15
  restart_app: ^1.2.1
  shared_preferences: ^2.2.0
  shorebird_code_push: ^1.1.3
  url_launcher: ^6.1.14

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  icons_launcher: ^2.1.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  package_rename: ^1.5.0
  very_good_analysis: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  #   ios: false
  image_path: "assets/logo/nice.png"
  #   adaptive_icon_background: "#005f00"
  adaptive_icon_foreground: "assets/logo/gb.png"
  # flutter_launcher_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   # image_path: "assets/icon/icon.png"
  #   image_path: "assets/logo/nice.png"
  #   min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   # image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/banner/
    - assets/animations/
    - shorebird.yaml
