name: deshifarmer
description: A agro flutter based project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.2.0
  animations: ^2.0.7
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.1.3
  # flutter_image_compress: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_widget_from_html: ^0.10.3
  http: ^1.1.0
  image_picker: ^1.0.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  multi_dropdown: ^2.0.1
  path_provider: ^2.0.15

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  # isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
