// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtd8x8Zj01F6ZN6-3eQ5b2ydXlUuMJ7Ag',
    appId: '1:1002083699883:web:85287dc9b73525acdd7bee',
    messagingSenderId: '1002083699883',
    projectId: 'deshifarmer-3d7cf',
    authDomain: 'deshifarmer-3d7cf.firebaseapp.com',
    storageBucket: 'deshifarmer-3d7cf.appspot.com',
    measurementId: 'G-T6P9JW4LF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7jRTTv7gDMmf-zZj0Mjfm0CY5uD3xfo',
    appId: '1:1002083699883:android:731b66f8f792b25add7bee',
    messagingSenderId: '1002083699883',
    projectId: 'deshifarmer-3d7cf',
    storageBucket: 'deshifarmer-3d7cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABnyfJ-L4cb2o22Dhp-NMvsQsMJNy9_qA',
    appId: '1:1002083699883:ios:dc75449be3ab88c0dd7bee',
    messagingSenderId: '1002083699883',
    projectId: 'deshifarmer-3d7cf',
    storageBucket: 'deshifarmer-3d7cf.appspot.com',
    iosBundleId: 'co.deshifarmer.me',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABnyfJ-L4cb2o22Dhp-NMvsQsMJNy9_qA',
    appId: '1:1002083699883:ios:0b0cf0a1a99bbd73dd7bee',
    messagingSenderId: '1002083699883',
    projectId: 'deshifarmer-3d7cf',
    storageBucket: 'deshifarmer-3d7cf.appspot.com',
    iosBundleId: 'com.deshifarmer.org.deshifarmer.RunnerTests',
  );
}
